In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv(r'Human_Age_Prediction.csv')
data.head()

,Gender,Height (cm),Weight (kg),Blood Pressure (s/d),Cholesterol Level (mg/dL),BMI,Blood Glucose Level (mg/dL),Bone Density (g/cm²),Vision Sharpness,Hearing Ability (dB),...,Family History,Cognitive Function,Mental Health Status,Sleep Patterns,Stress Levels,Pollution Exposure,Sun Exposure,Education Level,Income Level,Age (years)
0,Male,171.148359,86.185197,151/109,259.465814,29.423017,157.652848,0.132868,0.200000,58.786198,...,NaN,44.059172,Good,Insomnia,2.797064,5.142344,7.108975,NaN,Medium,89
1,Male,172.946206,79.641937,134/112,263.630292,26.626847,118.507805,0.629534,0.267312,54.635270,...,Heart Disease,45.312298,Good,Normal,9.339930,7.272720,3.918489,Undergraduate,Medium,77
2,Female,155.945488,49.167058,160/101,207.846206,20.217553,143.587550,0.473487,0.248667,54.564632,...,Hypertension,56.246991,Poor,Insomnia,9.234637,8.500386,5.393408,NaN,Medium,70
3,Female,169.078298,56.017921,133/94,253.283779,19.595270,137.448581,1.184315,0.513818,79.722963,...,Hypertension,55.196092,Poor,Insomnia,4.693446,7.555511,2.745578,NaN,Low,52
4,Female,163.758355,73.966304,170/106,236.119899,27.582078,145.328695,0.434562,0.306864,52.479469,...,NaN,53.023379,Good,Normal,4.038537,9.429097,3.878435,Undergraduate,High,79

In [4]:
data.isnull().sum()

Gender                            0
Height (cm)                       0
Weight (kg)                       0
Blood Pressure (s/d)              0
Cholesterol Level (mg/dL)         0
BMI                               0
Blood Glucose Level (mg/dL)       0
Bone Density (g/cm²)              0
Vision Sharpness                  0
Hearing Ability (dB)              0
Physical Activity Level           0
Smoking Status                    0
Alcohol Consumption            1201
Diet                              0
Chronic Diseases               1299
Medication Use                 1198
Family History                 1451
Cognitive Function                0
Mental Health Status              0
Sleep Patterns                    0
Stress Levels                     0
Pollution Exposure                0
Sun Exposure                      0
Education Level                 627
Income Level                      0
Age (years)                       0
dtype: int64

In [5]:
data = data.fillna(0)
data.isnull().sum()
data.head()

,Gender,Height (cm),Weight (kg),Blood Pressure (s/d),Cholesterol Level (mg/dL),BMI,Blood Glucose Level (mg/dL),Bone Density (g/cm²),Vision Sharpness,Hearing Ability (dB),...,Family History,Cognitive Function,Mental Health Status,Sleep Patterns,Stress Levels,Pollution Exposure,Sun Exposure,Education Level,Income Level,Age (years)
0,Male,171.148359,86.185197,151/109,259.465814,29.423017,157.652848,0.132868,0.200000,58.786198,...,0,44.059172,Good,Insomnia,2.797064,5.142344,7.108975,0,Medium,89
1,Male,172.946206,79.641937,134/112,263.630292,26.626847,118.507805,0.629534,0.267312,54.635270,...,Heart Disease,45.312298,Good,Normal,9.339930,7.272720,3.918489,Undergraduate,Medium,77
2,Female,155.945488,49.167058,160/101,207.846206,20.217553,143.587550,0.473487,0.248667,54.564632,...,Hypertension,56.246991,Poor,Insomnia,9.234637,8.500386,5.393408,0,Medium,70
3,Female,169.078298,56.017921,133/94,253.283779,19.595270,137.448581,1.184315,0.513818,79.722963,...,Hypertension,55.196092,Poor,Insomnia,4.693446,7.555511,2.745578,0,Low,52
4,Female,163.758355,73.966304,170/106,236.119899,27.582078,145.328695,0.434562,0.306864,52.479469,...,0,53.023379,Good,Normal,4.038537,9.429097,3.878435,Undergraduate,High,79

In [6]:
data['Gender'] = data['Gender'].map({"Male":1,"Female":0})
data.head()

,Gender,Height (cm),Weight (kg),Blood Pressure (s/d),Cholesterol Level (mg/dL),BMI,Blood Glucose Level (mg/dL),Bone Density (g/cm²),Vision Sharpness,Hearing Ability (dB),...,Family History,Cognitive Function,Mental Health Status,Sleep Patterns,Stress Levels,Pollution Exposure,Sun Exposure,Education Level,Income Level,Age (years)
0,1,171.148359,86.185197,151/109,259.465814,29.423017,157.652848,0.132868,0.200000,58.786198,...,0,44.059172,Good,Insomnia,2.797064,5.142344,7.108975,0,Medium,89
1,1,172.946206,79.641937,134/112,263.630292,26.626847,118.507805,0.629534,0.267312,54.635270,...,Heart Disease,45.312298,Good,Normal,9.339930,7.272720,3.918489,Undergraduate,Medium,77
2,0,155.945488,49.167058,160/101,207.846206,20.217553,143.587550,0.473487,0.248667,54.564632,...,Hypertension,56.246991,Poor,Insomnia,9.234637,8.500386,5.393408,0,Medium,70
3,0,169.078298,56.017921,133/94,253.283779,19.595270,137.448581,1.184315,0.513818,79.722963,...,Hypertension,55.196092,Poor,Insomnia,4.693446,7.555511,2.745578,0,Low,52
4,0,163.758355,73.966304,170/106,236.119899,27.582078,145.328695,0.434562,0.306864,52.479469,...,0,53.023379,Good,Normal,4.038537,9.429097,3.878435,Undergraduate,High,79

In [7]:
x = data.drop("Age (years)",axis = 1)
y = data["Age (years)"]

In [8]:
x[['Systolic_BP', 'Diastolic_BP']] = x['Blood Pressure (s/d)'].str.split('/', expand=True)

x['Systolic_BP'] = pd.to_numeric(x['Systolic_BP'])
x['Diastolic_BP'] = pd.to_numeric(x['Diastolic_BP'])
# drop_col = ["Education Level",'Alcohol Consumption','Family History',"Smoking Status","Income Level","Blood Pressure (s/d)"]
# x = x.drop(columns = drop_col)

x.head()

,Gender,Height (cm),Weight (kg),Blood Pressure (s/d),Cholesterol Level (mg/dL),BMI,Blood Glucose Level (mg/dL),Bone Density (g/cm²),Vision Sharpness,Hearing Ability (dB),...,Cognitive Function,Mental Health Status,Sleep Patterns,Stress Levels,Pollution Exposure,Sun Exposure,Education Level,Income Level,Systolic_BP,Diastolic_BP
0,1,171.148359,86.185197,151/109,259.465814,29.423017,157.652848,0.132868,0.200000,58.786198,...,44.059172,Good,Insomnia,2.797064,5.142344,7.108975,0,Medium,151,109
1,1,172.946206,79.641937,134/112,263.630292,26.626847,118.507805,0.629534,0.267312,54.635270,...,45.312298,Good,Normal,9.339930,7.272720,3.918489,Undergraduate,Medium,134,112
2,0,155.945488,49.167058,160/101,207.846206,20.217553,143.587550,0.473487,0.248667,54.564632,...,56.246991,Poor,Insomnia,9.234637,8.500386,5.393408,0,Medium,160,101
3,0,169.078298,56.017921,133/94,253.283779,19.595270,137.448581,1.184315,0.513818,79.722963,...,55.196092,Poor,Insomnia,4.693446,7.555511,2.745578,0,Low,133,94
4,0,163.758355,73.966304,170/106,236.119899,27.582078,145.328695,0.434562,0.306864,52.479469,...,53.023379,Good,Normal,4.038537,9.429097,3.878435,Undergraduate,High,170,106

In [9]:
x = x.drop(columns=['Gender', 'Blood Pressure (s/d)','Physical Activity Level',
 'Smoking Status',
 'Alcohol Consumption',
 'Diet',
 'Chronic Diseases',
 'Medication Use',
 'Family History',
 'Cognitive Function',
 'Mental Health Status',
 'Sleep Patterns','Education Level',
 'Income Level'])

print(x.columns)

Index(['Height (cm)', 'Weight (kg)', 'Cholesterol Level (mg/dL)', 'BMI',
       'Blood Glucose Level (mg/dL)', 'Bone Density (g/cm²)',
       'Vision Sharpness', 'Hearing Ability (dB)', 'Stress Levels',
       'Pollution Exposure', 'Sun Exposure', 'Systolic_BP', 'Diastolic_BP'],
      dtype='object')

In [10]:
label_encoder = LabelEncoder()
string_columns = x.select_dtypes(include=['object']).columns
for column in string_columns:
    x[column] = x[column].astype(str)
    x[column] = label_encoder.fit_transform(x[column])

In [11]:
print(x.columns)

Index(['Height (cm)', 'Weight (kg)', 'Cholesterol Level (mg/dL)', 'BMI',
       'Blood Glucose Level (mg/dL)', 'Bone Density (g/cm²)',
       'Vision Sharpness', 'Hearing Ability (dB)', 'Stress Levels',
       'Pollution Exposure', 'Sun Exposure', 'Systolic_BP', 'Diastolic_BP'],
      dtype='object')

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 45)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
# pca = PCA(n_components=5)
# x_train = pca.fit_transform(x_train)
# x_test = pca.fit_transform(x_test)

In [13]:
models = {
    'Support Vector Machine': SVC(),
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Linear Regression': LinearRegression(),
    'Random Forest Regressor': RandomForestRegressor(),
    'XGBoost Regressor': XGBRegressor()
}

rf_param_grid = {
    'n_estimators': [50, 100, 200],
    'max_features': ['log2', 'sqrt'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

# Hyperparameter tuning for XGBoost
xgb_param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'subsample': [0.5, 0.75, 1.0]
}

scores = {}

for name, model in models.items():
    if name == 'Random Forest Regressor':
        grid_search = GridSearchCV(model, rf_param_grid, cv=5, scoring='r2', n_jobs=-1)
        grid_search.fit(x_train, y_train)
        best_model = grid_search.best_estimator_
    elif name == 'XGBoost Regressor':
        grid_search = GridSearchCV(model, xgb_param_grid, cv=5, scoring='r2', n_jobs=-1)
        grid_search.fit(x_train, y_train)
        best_model = grid_search.best_estimator_
    else:
        best_model = model
        best_model.fit(x_train, y_train)

    y_pred = best_model.predict(x_test)
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test,y_pred)
    r2 = r2_score(y_test, y_pred)
    scores[name] = {'MSE': mse, 'R2': r2,"MAE":mae}

# Print the evaluation scores
for model_name, score in scores.items():
    print(f"{model_name}: MSE = {score['MSE']:.4f}, R2 = {score['R2']:.4f},MAE = {score['MAE']:.4f}")

Support Vector Machine: MSE = 52.3817, R2 = 0.8709,MAE = 5.6250
Logistic Regression: MSE = 47.9017, R2 = 0.8819,MAE = 5.5250
Linear Regression: MSE = 27.7347, R2 = 0.9316,MAE = 4.1385
Random Forest Regressor: MSE = 29.0401, R2 = 0.9284,MAE = 4.2576
XGBoost Regressor: MSE = 29.3705, R2 = 0.9276,MAE = 4.2811

In [14]:
scores_df = pd.DataFrame.from_dict(scores, orient='index')
print(scores_df)

                               MSE        R2       MAE
Support Vector Machine   52.381667  0.870852  5.625000
Logistic Regression      47.901667  0.881897  5.525000
Linear Regression        27.734684  0.931619  4.138461
Random Forest Regressor  29.040071  0.928401  4.257557
XGBoost Regressor        29.370492  0.927586  4.281135

In [15]:
print("Best Model: ")
print(scores_df.loc["Linear Regression"])

Best Model:
MSE    27.734684
R2      0.931619
MAE     4.138461
Name: Linear Regression, dtype: float64